services:
  - type: web
    name: django-websocket-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "daphne -b 0.0.0.0 -p $PORT your_project.asgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project.settings
      - key: REDIS_URL
        fromService:
          name: redis
          type: redis
          property: connectionString

  - type: redis
    name: redis
    maxmemoryPolicy: allkeys-lru
