# Generated by Django 5.2.4 on 2025-07-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatapp", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
